using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpeedBoostPower : MonoBehaviour
{

    public float bonusSpeed = 20f;
    Timer timer;
    [SerializeField] GameObject player;

    // Update is called once per frame
    void Awake()
    {
        timer = player.GetComponent<Timer>();
    }

    void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.tag == "Player")
        {
            timer.timerOn = true;
            
            collision.GetComponent<PlayerMovement>().SpeedBoost();
            Destroy(gameObject); 
        }
    }
}
